version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NEXTAUTH_SECRET: "your-secret-key-here"
      DATABASE_URL: "postgres://username:password@postgres:5432/mydatabase"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
