version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app:
    build: .
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}  # Pass the DATABASE_URL explicitly
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - db
    command: >
      sh -c "npx prisma migrate dev --name init && npm run dev"


volumes:
  postgres_data:
