import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import { createTheme, MantineProvider } from "@mantine/core";
import ProviderApp from "@/context/providerApp";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "gisrtasks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = createTheme({
    primaryColor: "violet",
  });

  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider  theme={theme}>
          <ProviderApp>{children}</ProviderApp>
        </MantineProvider>
      </body>
    </html>
  );
}
